#!/usr/bin/env python3
"""
cgroup-apply.py — turn the cgroup-limits.py CSV into systemd drop-ins and verify them.

  1. Read the CSV (output of cgroup-limits.py), one row per user / service.
  2. Resolve the target unit: login name -> user-<uid>.slice; *.service/*.scope/*.slice as-is.
  3. Generate drop-ins into a staging dir (default ./cgroup-analysis/dropins) for human review.
  4. --apply installs the staging tree into /etc/systemd/system/ and daemon-reloads (needs root).
  5. --verify checks two layers: `systemctl show` first, to confirm the settings are loaded
     into systemd (works even when the user is not logged in), then /sys/fs/cgroup to compare
     the actual kernel values, plus oom_kill / CPU throttling / PSI canary signals.

Stdlib only.

Examples:
  python3 cgroup-apply.py cgroup-analysis/cgroup_limits.csv            # generate only, review first
  sudo python3 cgroup-apply.py cgroup-analysis/cgroup_limits.csv --apply
  sudo python3 cgroup-apply.py cgroup-analysis/cgroup_limits.csv --verify --psi-warn 10
  sudo python3 cgroup-apply.py limits.csv --only alice,bob --apply --verify   # canary two users first
  python3 cgroup-apply.py limits.csv --all-units                # also limit *.service/*.scope
  python3 cgroup-apply.py --remove                              # list what would be removed (dry-run)
  sudo python3 cgroup-apply.py --remove --apply                 # actually remove everything
  sudo python3 cgroup-apply.py --remove --only alice --apply    # remove only alice's limits
"""
import argparse
import csv
import pwd
import re
import shutil
import subprocess
import sys
from pathlib import Path

CGROUP_ROOT = Path("/sys/fs/cgroup")
SYSTEMD_DIR = Path("/etc/systemd/system")
DROPIN_NAME = "50-cgroup-limits.conf"

# CSV columns -> systemd properties, written into the drop-in in this order.
PROPS = ["MemoryLow", "MemoryHigh", "MemoryMax", "CPUWeight", "CPUQuota", "IOWeight"]

CPU_PERIOD_US = 100_000  # period used to convert systemd CPUQuota to cpu.max


# unit resolution
def resolve_unit(name, allow_system, users_only=False):
    """Map a CSV service value to (unit name, section name, skip reason).

    The exporter emits the login name for user slices (or "user-<uid>" when the
    account has no passwd entry) and the raw unit name for system.slice units.
    This is the reverse mapping.
    """
    for suffix, section in ((".service", "Service"), (".scope", "Scope"), (".slice", "Slice")):
        if name.endswith(suffix):
            if users_only:
                return None, None, "system unit, not limited by default (--all-units overrides)"
            return name, section, None
    m = re.fullmatch(r"user-(\d+)", name)
    if m:
        uid = int(m.group(1))
    else:
        try:
            uid = pwd.getpwnam(name).pw_uid
        except KeyError:
            return None, None, f"account {name!r} not in passwd (offboarded? LDAP not reachable?)"
    if uid < 1000 and not allow_system:
        return None, None, f"uid {uid} < 1000, system accounts not limited by default (--allow-system overrides)"
    return f"user-{uid}.slice", "Slice", None


# step 1: generate
def generate(rows, label, staging, allow_system, source, users_only=False):
    staging = Path(staging)
    if staging.exists():
        shutil.rmtree(staging)
    plan, skipped = [], []
    for row in rows:
        name = row.get(label, "").strip()
        if not name:
            continue
        unit, section, why = resolve_unit(name, allow_system, users_only)
        if not unit:
            skipped.append((name, why))
            continue
        props = [(p, row[p].strip()) for p in PROPS if row.get(p, "").strip()]
        if not props:
            skipped.append((name, "no limit columns in the CSV"))
            continue
        d = staging / f"{unit}.d"
        d.mkdir(parents=True, exist_ok=True)
        body = [
            f"# Generated by cgroup-apply.py from {source}",
            f"# source row: {label}={name}",
            f"[{section}]",
            *[f"{k}={v}" for k, v in props],
            "",
        ]
        (d / DROPIN_NAME).write_text("\n".join(body))
        plan.append((name, unit, dict(props)))

    print(f"==> generated {len(plan)} drop-in(s) in {staging}/")
    for name, unit, props in plan:
        pretty = " ".join(f"{k}={v}" for k, v in props.items())
        print(f"    {name:<20} -> {unit}.d/{DROPIN_NAME}  {pretty}")
    for name, why in skipped:
        print(f"    (skip) {name:<15} {why}", file=sys.stderr)
    if not plan:
        sys.exit("!! nothing to generate.")
    return plan


# step 2: apply
def apply(staging):
    staging = Path(staging)
    installed = []
    for src in sorted(staging.glob(f"*.d/{DROPIN_NAME}")):
        dst = SYSTEMD_DIR / src.parent.name / src.name
        try:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        except PermissionError:
            sys.exit(f"!! cannot write {dst}; --apply needs root.")
        installed.append(dst)
    print(f"==> installed {len(installed)} file(s) into {SYSTEMD_DIR}/, running daemon-reload ...")
    r = subprocess.run(["systemctl", "daemon-reload"], text=True, capture_output=True)
    if r.returncode != 0:
        sys.exit(f"!! daemon-reload failed: {r.stderr.strip()}")
    print("==> done. Takes effect immediately for logged-in users; at next login otherwise.")
    print("    rollback: cgroup-apply.py --remove --apply (optionally with --only <user>).")


# remove
def unit_display(unit):
    """Map a unit name to its display name (user-<uid>.slice -> login name, others as-is)."""
    m = re.fullmatch(r"user-(\d+)\.slice", unit)
    if not m:
        return unit
    try:
        return pwd.getpwuid(int(m.group(1))).pw_name
    except KeyError:
        return unit.removesuffix(".slice")


def remove(users_only, only, exclude, do_apply):
    """Remove drop-ins installed by this script (matches DROPIN_NAME only; touches nothing else)."""
    entries = []
    for p in sorted(SYSTEMD_DIR.glob(f"*.d/{DROPIN_NAME}")):
        unit = p.parent.name.removesuffix(".d")
        if users_only and not re.fullmatch(r"user-\d+\.slice", unit):
            continue
        entries.append((unit_display(unit), unit, p))

    names = {n for n, _, _ in entries} | {u for _, u, _ in entries}
    if only:
        want = {s.strip() for s in only.split(",") if s.strip()}
        missing = want - names
        if missing:
            sys.exit(f"!! --only names with no installed limits (typo?): {', '.join(sorted(missing))}\n"
                     f"   currently installed: {', '.join(sorted(n for n, _, _ in entries)) or '(none)'}")
        entries = [e for e in entries if e[0] in want or e[1] in want]
    if exclude:
        drop = {s.strip() for s in exclude.split(",") if s.strip()}
        entries = [e for e in entries if e[0] not in drop and e[1] not in drop]
    if not entries:
        sys.exit(f"!! no matching {DROPIN_NAME} under {SYSTEMD_DIR} (nothing installed, or all "
                 f"filtered out; system units are only listed with --all-units).")

    print(f"==> {'removing' if do_apply else 'would remove (dry-run)'} {len(entries)} drop-in(s):")
    for name, unit, p in entries:
        print(f"    {name:<20} {p}")
    if not do_apply:
        print("\n(nothing deleted — review the list, then add --apply to remove and daemon-reload)")
        return
    for _, _, p in entries:
        try:
            p.unlink()
        except PermissionError:
            sys.exit(f"!! cannot delete {p}; --remove --apply needs root.")
        try:
            p.parent.rmdir()  # collect the .d dir if now empty; leftovers are one more thing systemd scans
        except OSError:
            pass
    r = subprocess.run(["systemctl", "daemon-reload"], text=True, capture_output=True)
    if r.returncode != 0:
        sys.exit(f"!! daemon-reload failed: {r.stderr.strip()}")
    print("==> removed and daemon-reloaded. Limits on logged-in users lift immediately "
          "(guaranteed after logout/login at the latest).")


# step 3a: verify, systemd config layer
def parse_size(s):
    """'300M' / '2G' -> bytes; empty / 'max' -> None ('%' values unsupported)."""
    s = (s or "").strip()
    if not s or s in ("max", "infinity") or s.endswith("%"):
        return None
    units = {"K": 1024, "M": 1024**2, "G": 1024**3, "T": 1024**4}
    if s[-1] in units:
        return int(float(s[:-1]) * units[s[-1]])
    return int(s)


def parse_quota(s):
    """'120%' -> cpu.max quota in microseconds."""
    s = (s or "").strip().rstrip("%")
    return int(float(s) / 100 * CPU_PERIOD_US) if s else None


def parse_timespan_usec(s):
    """systemd timespan -> microseconds. '1.32s'->1320000, '500ms'->500000, '1min 6s'->66000000."""
    s = (s or "").strip()
    if not s or s in ("infinity", "[not set]"):
        return None
    total, matched = 0.0, False
    for num, unit in re.findall(r"([\d.]+)\s*(h|min|ms|us|s)", s):
        total += float(num) * {"h": 3600e6, "min": 60e6, "s": 1e6, "ms": 1e3, "us": 1}[unit]
        matched = True
    return total if matched else None


def parse_weight(s):
    """Weight value from systemctl show -> int. '[not set]' or the unset sentinel -> None."""
    s = (s or "").strip()
    if not s or s == "[not set]" or s == str(2**64 - 1):
        return None
    try:
        return int(s)
    except ValueError:
        return None


def parse_sd_bytes(s):
    s = (s or "").strip()
    if not s or s == "infinity":
        return None
    try:
        return int(s)
    except ValueError:
        return None


# drop-in property -> (systemctl show property, shown-value parser, expected-value converter)
SD_CHECKS = [
    ("MemoryLow", "MemoryLow", parse_sd_bytes, parse_size),
    ("MemoryHigh", "MemoryHigh", parse_sd_bytes, parse_size),
    ("MemoryMax", "MemoryMax", parse_sd_bytes, parse_size),
    ("CPUWeight", "CPUWeight", parse_weight, lambda v: int(v) if v else None),
    ("CPUQuota", "CPUQuotaPerSecUSec", parse_timespan_usec,
     lambda v: float(v.rstrip("%")) / 100 * 1e6 if v.strip() else None),
    ("IOWeight", "IOWeight", parse_weight, lambda v: int(v) if v else None),
]


def systemd_show(unit, prop_names):
    r = subprocess.run(["systemctl", "show", unit, "--property", ",".join(prop_names)],
                       text=True, capture_output=True)
    if r.returncode != 0:
        return None, r.stderr.strip() or f"systemctl show failed (exit {r.returncode})"
    return {k: v for k, _, v in (line.partition("=") for line in r.stdout.splitlines())}, None


def check_systemd(unit, props):
    """Return (problems, skip note). Verify via systemctl show that the config is loaded."""
    want = ["LoadState"] + [sd for k, sd, _, _ in SD_CHECKS if props.get(k, "").strip()]
    shown, err = systemd_show(unit, want)
    if err:
        return [], f"systemd layer query failed: {err}"
    if shown.get("LoadState") == "not-found":
        return [], "unit not loaded by systemd yet (the slice appears at login/start; the drop-in applies then)"
    probs = []
    for prop, sd_prop, parse_shown, parse_want in SD_CHECKS:
        raw = props.get(prop, "").strip()
        if not raw:
            continue
        want_v = parse_want(raw)
        got_v = parse_shown(shown.get(sd_prop, ""))
        if want_v is not None and not close(got_v, want_v):
            probs.append(f"systemd: {sd_prop}={shown.get(sd_prop) or '?'} (expected {prop}={raw}"
                         f" ~ {round(want_v)}; drop-in not installed, or daemon-reload forgotten?)")
    return probs, None


# step 3b: verify, kernel actual-value layer
def cg_path(unit):
    return CGROUP_ROOT / ("user.slice" if unit.startswith("user-") else "system.slice") / unit


def read_file(p):
    try:
        return p.read_text().strip()
    except OSError:
        return None


def read_key(p, key):
    for line in (read_file(p) or "").splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0] == key:
            return int(parts[1])
    return None


def read_psi_avg10(p):
    m = re.search(r"some avg10=([\d.]+)", read_file(p) or "")
    return float(m.group(1)) if m else None


def close(actual, expect, tol=0.02):
    return actual is not None and expect is not None and abs(actual - expect) <= expect * tol


def check_cgroup(unit, props, psi_warn):
    """Return (problems, note, health summary). Compare kernel values and canary signals."""
    cg = cg_path(unit)
    if not cg.is_dir():
        return [], "cgroup does not exist (user not logged in / unit not running); verify the kernel layer after login", ""
    probs = []

    # did the limits actually land in the kernel
    for prop, fname in (("MemoryMax", "memory.max"), ("MemoryHigh", "memory.high"),
                        ("MemoryLow", "memory.low")):
        want = parse_size(props.get(prop, ""))
        if want is None:
            continue
        got = read_file(cg / fname)
        got_n = None if got in (None, "max") else int(got)
        if not close(got_n, want):
            probs.append(f"cgroup: {fname}={got} (expected {want})")
    want_q = parse_quota(props.get("CPUQuota", ""))
    if want_q is not None:
        got = (read_file(cg / "cpu.max") or "").split()
        got_q = None if not got or got[0] == "max" else int(got[0])
        if not close(got_q, want_q):
            probs.append(f"cgroup: cpu.max={' '.join(got) or '?'} (expected {want_q} {CPU_PERIOD_US})")

    # canary health signals: the limit must bite without killing anyone
    oom = read_key(cg / "memory.events", "oom_kill")
    if oom:
        probs.append(f"cgroup: oom_kill={oom} — processes were killed, MemoryMax too tight")
    thr = read_key(cg / "cpu.stat", "nr_throttled")
    psi_mem = read_psi_avg10(cg / "memory.pressure")
    psi_cpu = read_psi_avg10(cg / "cpu.pressure")
    if psi_mem is not None and psi_mem > psi_warn:
        probs.append(f"cgroup: memory PSI some avg10={psi_mem} (> {psi_warn}; heavy reclaim pressure, "
                     f"MemoryHigh too tight)")
    return probs, "", f"(nr_throttled={thr}, psi cpu={psi_cpu} mem={psi_mem})"


def verify(plan, psi_warn):
    print("==> verify: (1) systemd config layer via systemctl show, "
          "(2) kernel values via /sys/fs/cgroup, plus canary signals")
    bad = 0
    for name, unit, props in plan:
        sd_probs, sd_note = check_systemd(unit, props)
        cg_probs, cg_note, health = check_cgroup(unit, props, psi_warn)
        probs = sd_probs + cg_probs
        notes = [n for n in (sd_note, cg_note) if n]
        if probs:
            bad += 1
            print(f"    ✗ {name:<18} {unit}")
            for p in probs:
                print(f"        - {p}")
        elif sd_note:
            print(f"    - {name:<18} {unit} not verifiable yet")
        else:
            ok = "config loaded" + ("" if cg_note else ", kernel values applied, no OOM " + health)
            print(f"    ✓ {name:<18} {unit} {ok}")
        for n in notes:
            print(f"        ({n})")
    if bad:
        sys.exit(f"!! {bad} unit(s) with problems, see above.")
    print("==> all checks passed.")


def main():
    p = argparse.ArgumentParser(description="CSV -> systemd drop-ins -> apply -> verify")
    p.add_argument("csv", nargs="?", help="CSV produced by cgroup-limits.py (not needed with --remove)")
    p.add_argument("--remove", action="store_true",
                   help="remove limits installed by this script (dry-run by default; add --apply to "
                        "actually delete and daemon-reload)")
    p.add_argument("--label", default="service", help="CSV column identifying the user (same as cgroup-limits.py)")
    p.add_argument("--only", help="process only these users/units, comma-separated (canary; unknown names abort)")
    p.add_argument("--exclude", help="skip these users/units, comma-separated")
    p.add_argument("--staging", default="./cgroup-analysis/dropins", help="output dir for generated drop-ins")
    p.add_argument("--all-units", action="store_true",
                   help="also limit system units (*.service/*.scope); by default only login users' "
                        "user-<uid>.slice are handled")
    p.add_argument("--users-only", action="store_true", help=argparse.SUPPRESS)  # now the default; kept for compat
    p.add_argument("--allow-system", action="store_true", help="also limit system accounts with uid < 1000")
    p.add_argument("--apply", action="store_true", help="install into /etc/systemd/system and daemon-reload (needs root)")
    p.add_argument("--verify", action="store_true", help="compare systemd and /sys/fs/cgroup values, run canary checks")
    p.add_argument("--psi-warn", type=float, default=10.0, help="memory PSI some avg10 warning threshold (default 10)")
    a = p.parse_args()

    if a.remove:
        remove(not a.all_units, a.only, a.exclude, a.apply)
        return
    if not a.csv:
        p.error("a CSV file is required (use --remove to clear limits)")

    with open(a.csv, newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        sys.exit(f"!! {a.csv} is empty.")

    def names_of(rows):
        return {r.get(a.label, "").strip() for r in rows}

    if a.only:
        want = {s.strip() for s in a.only.split(",") if s.strip()}
        missing = want - names_of(rows)
        if missing:
            sys.exit(f"!! --only names not in the CSV (typo?): {', '.join(sorted(missing))}\n"
                     f"   the CSV has: {', '.join(sorted(names_of(rows)))}")
        rows = [r for r in rows if r.get(a.label, "").strip() in want]
    if a.exclude:
        drop = {s.strip() for s in a.exclude.split(",") if s.strip()}
        unknown = drop - names_of(rows)
        if unknown:
            print(f"    (note) --exclude names not in the CSV: {', '.join(sorted(unknown))}", file=sys.stderr)
        rows = [r for r in rows if r.get(a.label, "").strip() not in drop]
    if not rows:
        sys.exit("!! no rows left after filtering.")

    plan = generate(rows, a.label, a.staging, a.allow_system, a.csv, users_only=not a.all_units)
    if a.apply:
        apply(a.staging)
    else:
        print("\n(not applied yet — review the values above, then add --apply, "
              "or publish the staging dir with Ansible)")
    if a.verify:
        verify(plan, a.psi_warn)


if __name__ == "__main__":
    main()
